#!/usr/bin/env bash
# Regenerates Generated/Validation.cs from Validation.dfy. Verification happens as part of translation;
# a Dafny proof failure aborts generation. Run from anywhere; requires `dotnet tool restore` (Dafny) once.
set -euo pipefail
cd "$(dirname "$0")"

dotnet tool run dafny -- translate cs --include-runtime --output:Generated/Validation Validation.dfy

# Prepend the auto-generated marker so Roslyn analyzers treat the file as generated code.
tmp=$(mktemp)
{
  echo "// <auto-generated/>"
  echo "// Compiled from Validation.dfy by 'dafny translate cs' — do not edit; run generate.sh instead."
  cat Generated/Validation.cs
} > "$tmp"
mv "$tmp" Generated/Validation.cs
echo "Wrote $(pwd)/Generated/Validation.cs"
