using System.Globalization;
using System.Text;

namespace Wallymathieu.Auctions.Tools.CSharpToDafny;

/// <summary>
///     Emits Dafny source files from extracted methods: a shared <c>Types.dfy</c> prelude plus one file per
///     containing C# type. Output is deterministic so that CI can detect drift with a plain diff.
/// </summary>
internal static class DafnyEmitter
{
    private const string Header = "// Generated by tools/CSharpToDafny — do not edit by hand.";

    public static IReadOnlyDictionary<string, string> Emit(IReadOnlyList<VerifiedMethod> methods, TypeRegistry registry)
    {
        var files = new SortedDictionary<string, string>(StringComparer.Ordinal)
        {
            ["Types.dfy"] = EmitTypes(registry)
        };
        foreach (var group in methods.GroupBy(m => (m.ContainingNamespace, m.ContainingType)))
        {
            files[$"{group.Key.ContainingType}.dfy"] = EmitTypeFile(group.Key.ContainingNamespace, group.Key.ContainingType, [.. group]);
        }

        return files;
    }

    private static string EmitTypes(TypeRegistry registry)
    {
        var builder = new StringBuilder();
        builder.AppendLine(Header);
        builder.AppendLine("module GeneratedTypes {");
        if (registry.UsesTime)
        {
            builder.AppendLine();
            builder.AppendLine("  // System.DateTimeOffset modelled as integer ticks: a total order is all the specifications need.");
            builder.AppendLine("  type Time = int");
        }

        foreach (var (name, fullName) in registry.OpaqueTypes)
        {
            builder.AppendLine();
            builder.AppendLine(CultureInfo.InvariantCulture, $"  // {fullName}: opaque type supporting equality.");
            builder.AppendLine(CultureInfo.InvariantCulture, $"  type {name}(==)");
        }

        foreach (var enumModel in registry.Enums.Values)
        {
            builder.AppendLine();
            builder.AppendLine(enumModel.IsFlags
                ? $"  // {enumModel.FullName}: [Flags] enum modelled as a 32-bit vector so `|` and `&` translate directly."
                : $"  // {enumModel.FullName}: enum modelled as a 32-bit vector.");
            builder.AppendLine(CultureInfo.InvariantCulture, $"  type {enumModel.Name} = bv32");
            foreach (var (member, value) in enumModel.Members)
            {
                builder.AppendLine(CultureInfo.InvariantCulture, $"  const {enumModel.Name}_{member}: {enumModel.Name} := {value}");
            }
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string EmitTypeFile(string containingNamespace, string typeName, IReadOnlyList<VerifiedMethod> methods)
    {
        var builder = new StringBuilder();
        builder.AppendLine(Header);
        builder.AppendLine(CultureInfo.InvariantCulture, $"// Skeletons extracted from {containingNamespace}.{typeName}. The {{:axiom}} attribute marks each");
        builder.AppendLine("// contract as assumed until a verified Dafny implementation replaces the skeleton (see verification/Dafny).");
        builder.AppendLine("include \"Types.dfy\"");
        builder.AppendLine();
        builder.AppendLine(CultureInfo.InvariantCulture, $"module Generated_{containingNamespace.Replace('.', '_')}_{typeName} {{");
        builder.AppendLine("  import opened GeneratedTypes");
        foreach (var method in methods)
        {
            builder.AppendLine();
            builder.AppendLine(CultureInfo.InvariantCulture, $"  // {containingNamespace}.{typeName}.{method.Name} ({method.SourcePath}:{method.SourceLine})");
            var parameters = string.Join(", ", method.Parameters.Select(p => $"{p.Name}: {p.DafnyType}"));
            builder.AppendLine(CultureInfo.InvariantCulture, $"  method {{:axiom}} {method.Name}({parameters})");
            builder.AppendLine(CultureInfo.InvariantCulture, $"    returns ({method.ResultName}: {method.ReturnDafnyType})");
            foreach (var requires in method.RequiresClauses)
            {
                builder.AppendLine(CultureInfo.InvariantCulture, $"    requires {requires}");
            }

            foreach (var ensures in method.EnsuresClauses)
            {
                builder.AppendLine(CultureInfo.InvariantCulture, $"    ensures {ensures}");
            }

            foreach (var untranslated in method.UntranslatedClauses)
            {
                builder.AppendLine(CultureInfo.InvariantCulture, $"    // TODO(unsupported contract): {SanitizeComment(untranslated)}");
            }

            if (method.OriginalBody.Length > 0)
            {
                builder.AppendLine("  /* Original C# body:");
                foreach (var line in method.OriginalBody.Split('\n'))
                {
                    builder.AppendLine(CultureInfo.InvariantCulture, $"  {SanitizeComment(line.TrimEnd())}");
                }

                builder.AppendLine("  */");
            }
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string SanitizeComment(string text)
    {
        return text.Replace("*/", "* /", StringComparison.Ordinal);
    }
}
