<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Wallymathieu.Auctions</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <!--disable missing comment warning-->
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Auctions.Infrastructure"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auctions.Domain.Verified\Auctions.Domain.Verified.csproj" />
  </ItemGroup>
</Project>
